targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragmens_glob: graphql/*.fragment.graphql
          schema_mapping:
              - schema: schema.graphql
                output: lib/data_layer/data_sources/network/graphql/queries/graphql_queries.dart
                queries_glob: graphql/*.query.graphql